### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Joannis** [vapor/multipart#11]
https://github.com/vapor/multipart/blob/master/Sources/Multipart/BoundaryParser.swift#L35

Copying every single byte of a multipart upload to a new buffer one-by-one. It's really destructive for performance.

**Comment by tanner0101** [comment]
That's only for parsing boundaries which is arguably negligible. The content of the upload is not copied byte by byte. https://github.com/vapor/multipart/blob/master/Sources/Multipart/Parser.swift#L227

**Comment by tanner0101** [comment]
Closing since this is a "general" performance issue and not related to a specific bug or feature request.
